# Generated by Django 5.2.8 on 2025-11-25 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='对象ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='用户名')),
                ('user_email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('comment', models.TextField(verbose_name='评论内容')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='层级')),
                ('thread_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='线程ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('is_removed', models.BooleanField(default=False, verbose_name='是否删除')),
                ('submit_date', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('site_id', models.PositiveIntegerField(default=1, verbose_name='站点ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='内容类型')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comment.comment', verbose_name='父评论')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['thread_id', 'order', 'submit_date'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='comment_com_content_209058_idx'), models.Index(fields=['thread_id'], name='comment_com_thread__bdbb29_idx'), models.Index(fields=['is_public', 'is_removed'], name='comment_com_is_publ_84b623_idx')],
            },
        ),
    ]
