# Generated by Django 5.2.8 on 2025-11-18 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session', models.CharField(db_index=True, help_text='存储用户的 session key', max_length=40, verbose_name='用户会话ID')),
                ('reaction_type', models.CharField(choices=[('like', '点赞'), ('dislike', '点踩')], max_length=10, verbose_name='反应类型')),
                ('object_id', models.PositiveIntegerField(verbose_name='对象ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='内容类型')),
            ],
            options={
                'verbose_name': '用户反应',
                'verbose_name_plural': '用户反应',
                'db_table': 'reactions_user_reaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='reactions_u_content_831f0c_idx'), models.Index(fields=['user_session'], name='reactions_u_user_se_dd85a7_idx'), models.Index(fields=['-created_at'], name='reactions_u_created_05eaf4_idx')],
                'unique_together': {('user_session', 'content_type', 'object_id')},
            },
        ),
    ]
