# Generated by Django 5.2.8 on 2025-11-27 22:51

import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('姓名', models.CharField(max_length=100, verbose_name='姓名')),
                ('邮箱', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('建议内容', models.TextField(verbose_name='建议内容')),
                ('提交时间', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('已处理', models.BooleanField(default=False, verbose_name='已处理')),
                ('处理备注', models.TextField(blank=True, null=True, verbose_name='处理备注')),
            ],
            options={
                'verbose_name': '用户反馈',
                'verbose_name_plural': '用户反馈',
                'ordering': ['-提交时间'],
            },
        ),
        migrations.AlterField(
            model_name='论文',
            name='图片',
            field=sorl.thumbnail.fields.ImageField(default='null', null=True, upload_to='images/lunwen/'),
        ),
    ]
