# Generated by Django 5.2.8 on 2025-11-28 16:07

import home.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_feedback_alter_论文_图片'),
    ]

    operations = [
        migrations.AlterField(
            model_name='书库',
            name='文档',
            field=models.FileField(storage=home.storage.CompressedFileSystemStorage(), upload_to='pdf/shuku/', verbose_name='PDF文档'),
        ),
        migrations.AlterField(
            model_name='古籍',
            name='文档',
            field=models.FileField(storage=home.storage.CompressedFileSystemStorage(), upload_to='pdf/guji/', verbose_name='PDF文档'),
        ),
        migrations.AlterField(
            model_name='论文',
            name='文档',
            field=models.FileField(default='null', null=True, storage=home.storage.CompressedFileSystemStorage(), upload_to='pdf/lunwen/', verbose_name='PDF文档'),
        ),
    ]
