# Generated by Django 5.2.8 on 2025-11-26 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HadithCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='圣训集全称')),
                ('short_name', models.CharField(max_length=20, unique=True, verbose_name='简称')),
                ('arabic_name', models.CharField(blank=True, max_length=100, verbose_name='阿拉伯文名称')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
                ('total_hadiths', models.PositiveIntegerField(default=0, verbose_name='总条数')),
                ('is_sahih', models.BooleanField(default=False, verbose_name='是否两大真本')),
            ],
            options={
                'verbose_name': '圣训集',
                'verbose_name_plural': '圣训集管理',
            },
        ),
        migrations.CreateModel(
            name='Hadith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=200, verbose_name='章节标题')),
                ('collection_number', models.CharField(max_length=30, verbose_name='本集编号')),
                ('text', models.TextField(verbose_name='正文')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hadiths', to='hadith.hadithcollection', verbose_name='所属圣训集')),
            ],
            options={
                'verbose_name': '圣训',
                'verbose_name_plural': '全部圣训',
                'ordering': ['collection', 'chapter', 'collection_number'],
                'unique_together': {('collection', 'collection_number')},
            },
        ),
    ]
