# Generated by Django 5.2.8 on 2025-11-25 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session', models.CharField(db_index=True, max_length=40, verbose_name='用户会话ID')),
                ('reaction_type', models.CharField(choices=[('like', '点赞'), ('dislike', '踩')], max_length=10, verbose_name='反应类型')),
                ('object_id', models.PositiveIntegerField(verbose_name='对象ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='内容类型')),
            ],
            options={
                'verbose_name': '用户反应记录',
                'verbose_name_plural': '用户反应记录',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='interaction_content_a39182_idx'), models.Index(fields=['user_session'], name='interaction_user_se_0d22b0_idx')],
                'unique_together': {('user_session', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='对象ID')),
                ('总浏览量', models.PositiveIntegerField(db_index=True, default=0, verbose_name='总浏览量')),
                ('今日浏览量', models.PositiveIntegerField(db_index=True, default=0, verbose_name='今日浏览量')),
                ('最后统计日期', models.DateField(auto_now=True, verbose_name='最后统计日期')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='内容类型')),
            ],
            options={
                'verbose_name': '浏览量统计',
                'verbose_name_plural': '浏览量统计',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='interaction_content_3e9ec8_idx')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
