# Generated by Django 5.2.8 on 2025-11-25 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session', models.CharField(db_index=True, max_length=40, verbose_name='用户会话ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='对象ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='访问时间')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='内容类型')),
            ],
            options={
                'verbose_name': '访问记录',
                'verbose_name_plural': '访问记录',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'viewed_at'], name='interaction_content_afff70_idx'), models.Index(fields=['user_session', 'content_type', 'object_id', 'viewed_at'], name='interaction_user_se_56f79f_idx'), models.Index(fields=['user_session', 'viewed_at'], name='interaction_user_se_bdd1b4_idx')],
            },
        ),
    ]
